name:                jord
version:             0.3.0.0
github:              ofmooseandmen/jord
license:             BSD3
author:              Cedric Liegeois
maintainer:          Cedric Liegeois <ofmooseandmen@yahoo.com>
copyright:           2018 Cedric Liegeois
category:            Geography
stability:           experimental
homepage:            https://github.com/ofmooseandmen/jord
synopsis:            Geographical Position Calculations
description:         Please see the README on GitHub at <https://github.com/ofmooseandmen/jord#readme>

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Geo.Jord
    - Data.Geo.Jord.Angle
    - Data.Geo.Jord.Ellipsoid
    - Data.Geo.Jord.Ellipsoidal
    - Data.Geo.Jord.LatLong
    - Data.Geo.Jord.Length
    - Data.Geo.Jord.NedVector
    - Data.Geo.Jord.NVector
    - Data.Geo.Jord.Positions
    - Data.Geo.Jord.Quantity
    - Data.Geo.Jord.Spherical
    - Data.Geo.Jord.Transform
  other-modules:
    - Data.Geo.Jord.Parse

executables:
  jord-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - jord
    - haskeline >= 0.7 && < 0.8

tests:
  jord-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - jord
    - hspec == 2.*
    - HUnit == 1.6.*
