name:                jord
version:             0.1.0.0
github:              ofmooseandmen/jord
license:             BSD3
author:              Cedric Liegeois
maintainer:          Cedric Liegeois <ofmooseandmen@yahoo.com>
copyright:           2018 Cedric Liegeois
category:            Geography
stability:           experimental
homepage:            https://ofmooseandmen.github.io/jord
synopsis:            Geographic position calculations on Great Circles
description:         Please see the README on GitHub at <https://github.com/ofmooseandmen/jord#readme>

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Geo.Jord
    - Data.Geo.Jord.Angle
    - Data.Geo.Jord.Length
    - Data.Geo.Jord.GeoPos
    - Data.Geo.Jord.GreatCircle
    - Data.Geo.Jord.Quantity
    - Data.Geo.Jord.NVector
  other-modules:
    - Data.Geo.Jord.Parse

executables:
  jord-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - jord

tests:
  jord-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - jord
    - hspec == 2.*
    - HUnit == 1.6.*
