name:                jord
version:             1.0.0.0
github:              ofmooseandmen/jord
license:             BSD3
author:              Cedric Liegeois
maintainer:          Cedric Liegeois <ofmooseandmen@yahoo.com>
copyright:           2019 Cedric Liegeois
category:            Geography
stability:           experimental
homepage:            https://github.com/ofmooseandmen/jord
synopsis:            Geographical Position Calculations
description:         Please see the README on GitHub at <https://github.com/ofmooseandmen/jord#readme>

extra-source-files:
- README.md
- ChangeLog.md

ghc-options: -Wall

dependencies:
- base >= 4.9 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Geo.Jord
    - Data.Geo.Jord.Angle
    - Data.Geo.Jord.Bodies
    - Data.Geo.Jord.Duration
    - Data.Geo.Jord.Frames
    - Data.Geo.Jord.Geodesic
    - Data.Geo.Jord.GreatCircle
    - Data.Geo.Jord.Kinematics
    - Data.Geo.Jord.LatLong
    - Data.Geo.Jord.Length
    - Data.Geo.Jord.Position
    - Data.Geo.Jord.Quantity
    - Data.Geo.Jord.Rotation
    - Data.Geo.Jord.Speed
    - Data.Geo.Jord.Vector3d
  other-modules:
    - Data.Geo.Jord.Parser
    - Data.Geo.Jord.Spherical

executables:
  jord-repl:
    main:                Main.hs
    other-modules:
      - Eval
      - Show
      - State
    source-dirs:         app
    dependencies:
    - jord
    - haskeline >= 0.7 && < 0.8
  jord-benchmarks:
    main:                Main.hs
    other-modules:
      - GeodeticsBG
      - KinematicsBG
      - TransformationBG
    source-dirs:         benchmarks
    dependencies:
    - jord
    - criterion

tests:
  jord-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - jord
    - hspec == 2.*
    - HUnit == 1.6.*
